# SearXNG settings

use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "ultra-secret-key-change-me" # You should change this
  base_url: http://localhost:8080/
  public_instance: false # This disables some stricter protections intended for public deployments.

search:
  formats:
    - html
    - json
  safe_search: 0
  autocomplete: ""


limiter: false

engines:
  # - name: google
  #   engine: google
  #   shortcut: g

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  # - name: google news
  #   disabled: true

  # - name: bing
  #   engine: bing
  #   shortcut: b

valkey:
  url: redis://redis:6379/0
